spin_manifest_version = 2

[application]
name = "message-logger"
version = "0.1.0"
authors = ["Danielle Lancashire <dani@builds.terrible.systems>"]
description = ""

[[trigger.http]]
route = "/..."
component = "message-logger"

[component.message-logger]
source = "target/wasm32-wasi/release/message_logger.wasm"
allowed_outbound_hosts = []
[component.message-logger.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
